### ISSUE TITLE
Error in example/auth_userpass.js

### ISSUE THREAD

**Issue by kr1sp1n** [kr1sp1n/node-vault#66] opened 2017-10-02 18:56 UTC
When I execute `node example/auth_userpass.js` I get the following error:
```
authentication backends cannot create root tokens
```

**Comment by jmls** [comment] 2018-01-18 11:25
any news on this ?

**Comment by DaniGuardiola** [comment] 2018-02-26 13:40
Duplicate of #79

**Closed by DaniGuardiola** 2018-02-26 13:40 UTC
Labels: bug
