### ISSUE TITLE
Error: Vault is already initialized

### ISSUE THREAD

**Issue by theRemix** [kr1sp1n/node-vault#84] opened 2018-04-27 04:47 UTC
I have a vault server running at localhost:8200

going through the example code is giving me the `Error: Vault is already initialized`

```javascript
var vault = require("node-vault")();

vault.init({ secret_shares: 1, secret_threshold: 1 })
.then((result) => {
  console.log(result);
  vault.token = result.root_token;
  const key = result.keys[0];
  return vault.unseal({ secret_shares: 1, key });
})
.catch(err => console.error(err));
```

this also doesn't work for me 

```javascript
var vault = require("node-vault")();

vault.initialized()
.then((result) => {
  console.log(result); // { initialized : true }
  return vault.init({ secret_shares: 1, secret_threshold: 1 });
})
.then((result) => { // doesn't resolve because vault is already initialized
  console.log(result);
  vault.token = result.root_token;
  const key = result.keys[0];
  return vault.unseal({ secret_shares: 1, key });
})
.then(console.log)
.catch((err) => console.error(err.message));
```

how do i get the root_token?

I am using [boostport/kubernetes-vault](https://github.com/Boostport/kubernetes-vault)
so i do have access to the vault-token.
```json
{
   "clientToken":"91526d9b-4850-3405-02a8-aa29e74e17a5",
   "accessor":"476ea048-ded5-4d07-eeea-938c6b4e43ec",
   "leaseDuration":3600,
   "renewable":true,
   "vaultAddr":"https://vault:8200"
}
```

is there a way i can read vault secrets with the `clientToken`?

```javascript
var vault = require("node-vault")({
  token : clientToken,
  endpoint : vaultAddr
});

vault.initialized()
.then((result) => {
  console.log(result); // { initialized : true }
  return vault.read('database/config/prod-pg');
})
.then(dbConfig => {
  console.log('DB Config', dbConfig);
})
.catch((err) => console.error(err.message)); // Error: permission denied

```

returns `Error: permission denied`

**Comment by DaniGuardiola** [comment] 2018-04-27 15:35
For the first issue you mention, seems like you are trying to initialize an already initialized vault instance. Check the vault status with the vault cli to assert this.

For the second issue regarding using the client token to retrieve a secret, that seems like an issue of the client not having the needed permissions. You can also check this by using the vault cli again, authenticating with the client token and trying to retrieve the secret.

**Comment by DaniGuardiola** [comment] 2018-04-27 15:36
I'm closing this for now as it seems like the problem is not `node-vault` related.

**Closed by DaniGuardiola** 2018-04-27 15:36 UTC

**Comment by theRemix** [comment] 2018-05-08 05:47
yes you were right. the clientToken did not have sufficient access to get that secret.
i updated the policy so the appRole is authorized, and tested with the cli as you said.

everything works now. Thanks!

i _do_ think the docs and examples could be a bit more descriptive.
